// JumpDetector: the interface between the IMU and the rest of the firmware.
// You normally do not edit this file; derive a class from JumpDetector (see MyJumpDetector.h)
// and select it in the "Algorithm selection" block at the top of the .ino.
#pragma once

#include "../config/FirmwareConfig.h"
#include "ImuTypes.h"
#include "Transition.h"

class JumpDetector {
 public:
  virtual ~JumpDetector() {}

  // Name of your algorithm, e.g. "EnvelopeDetector v3". It is shown over BLE (Software Revision
  // String, at most 32 bytes) so you can see which algorithm is running on a device.
  virtual const char* name() const { return "unnamed detector"; }

  // Which IMU settings your algorithm wants. Override to force one, e.g.
  //   const ImuProfile& imuProfile() const override { return PROFILE_833HZ_16G; }
  // The default follows IMU_USE_HIGH_RATE_PROFILE.
  virtual const ImuProfile& imuProfile() const {
    return IMU_USE_HIGH_RATE_PROFILE ? PROFILE_833HZ_16G : PROFILE_416HZ_8G;
  }

  // Called once at start-up, after the IMU is running. Reset your state here.
  virtual void begin() {}

  // Called for every IMU sample, in time order.
  virtual void onSample(const ImuData& s) = 0;

  // ---- used by the firmware to collect what your algorithm reported ----
  bool nextTransition(Transition& out) {
    if (_count == 0) return false;
    out = _queue[_head];
    _head = (_head + 1) % QUEUE_SIZE;
    _count--;
    return true;
  }

 protected:
  // Call when the gymnast LEAVES the bed. `timeUs` normally is s.timeUs of the current sample;
  // if your detector notices it late you may pass an earlier time (e.g. s.timeUs - delayUs).
  void takeoff(uint64_t timeUs) { push(TRANSITION_TAKEOFF, timeUs); }

  // Call when the gymnast LANDS on the bed. Same rules for `timeUs`.
  void landing(uint64_t timeUs) { push(TRANSITION_LANDING, timeUs); }

 private:
  static const int QUEUE_SIZE = 8;
  Transition _queue[QUEUE_SIZE];
  int _head = 0;
  int _count = 0;

  void push(TransitionType type, uint64_t timeUs) {
    if (_count >= QUEUE_SIZE) return;  // cannot happen if the firmware keeps up
    _queue[(_head + _count) % QUEUE_SIZE] = {type, timeUs};
    _count++;
  }
};
